import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './css/global.css';
import { Header } from './components/Layout/Header';
import { Footer } from './components/Layout/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next13 App',
  description: 'Generated by create next 13 app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}

export default RootLayout;